/*
 * Copyright © 2026 Borg GPU project
 * SPDX-License-Identifier: MIT
 *
 * borgc-cli — compile a SPIR-V module to a Borg .borg shader blob, offline.
 *
 * Why this exists: borgc previously ran ONLY inside borgvk at vkQueueSubmit
 * time, which meant the compiler could not be exercised without standing up a
 * Vulkan app, a driver and a device. Two consequences followed from that, both
 * of which this removes:
 *
 *   - The firmware's baked shader blobs (software/borg/compiler/shader_blobs.h)
 *     were generated by a pipeline that has since been deleted, and could not
 *     be regenerated. They are a fossil that silently rots when the ISA or the
 *     wire format moves under them -- which had already happened once.
 *   - The golden-image render replays a *recorded* borgvk byte stream, so it
 *     cannot catch a borgc regression. A shader compiled here can be baked into
 *     the firmware, at which point the render tests the compiler on every run.
 *
 * It shares its SPIR-V options and NIR pass list with the driver
 * (borg_nir_passes.c) rather than copying them, so the two cannot diverge --
 * an offline-compiled shader is the same code the driver would produce.
 */
#include "borg_nir_passes.h"

#include "compiler/glsl_types.h"
#include "util/ralloc.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void
usage(const char *argv0)
{
   fprintf(stderr,
      "usage: %s [-s vert|frag] [-e entry] [-n name] [-H out.h] [-o out.borg] in.spv\n"
      "\n"
      "  -s  shader stage (default: vert)\n"
      "  -e  SPIR-V entry point (default: main)\n"
      "  -n  C identifier for -H output (default: derived from -o)\n"
      "  -o  write the raw .borg blob here\n"
      "  -H  write a C header declaring <name>[] and <name>_len\n"
      "\n"
      "Environment: BORGC_DUMP_NIR, BORGC_DUMP_ISA, BORGC_FRAG_ALPHA, BORGC_LEGACY\n",
      argv0);
}

static uint32_t *
read_spirv(const char *path, size_t *word_count)
{
   FILE *f = fopen(path, "rb");
   if (!f) {
      fprintf(stderr, "borgc-cli: cannot open %s\n", path);
      return NULL;
   }
   fseek(f, 0, SEEK_END);
   long sz = ftell(f);
   fseek(f, 0, SEEK_SET);
   /* SPIR-V is a stream of 32-bit words; a size that is not a multiple of 4
    * is not a truncated module we should try to compile, it is not SPIR-V. */
   if (sz <= 0 || (sz % 4) != 0) {
      fprintf(stderr, "borgc-cli: %s is %ld bytes, not a whole number of "
                      "SPIR-V words\n", path, sz);
      fclose(f);
      return NULL;
   }
   uint32_t *words = malloc(sz);
   if (!words || fread(words, 1, sz, f) != (size_t)sz) {
      fprintf(stderr, "borgc-cli: short read on %s\n", path);
      free(words);
      fclose(f);
      return NULL;
   }
   fclose(f);
   *word_count = sz / 4;
   return words;
}

static int
write_header(const char *path, const char *name, const uint8_t *blob, uint32_t len)
{
   FILE *f = fopen(path, "w");
   if (!f) {
      fprintf(stderr, "borgc-cli: cannot write %s\n", path);
      return 1;
   }
   fprintf(f, "// Generated by borgc-cli. Do not edit.\n"
              "//\n"
              "// Regenerate with the rule that produced it rather than by hand:\n"
              "// this is compiler output, and hand-editing is how the previous\n"
              "// generation of these blobs became unregenerable.\n"
              "#pragma once\n#include <stdint.h>\n\n");
   fprintf(f, "unsigned char %s[] = {", name);
   for (uint32_t i = 0; i < len; i++)
      fprintf(f, "%s0x%02x%s", (i % 12) == 0 ? "\n  " : " ", blob[i],
              (i + 1 < len) ? "," : "");
   fprintf(f, "\n};\nunsigned int %s_len = %u;\n", name, len);
   fclose(f);
   return 0;
}

int
main(int argc, char **argv)
{
   const char *stage_name = "vert", *entry = "main", *out = NULL;
   const char *hdr = NULL, *name = NULL, *in = NULL;

   for (int i = 1; i < argc; i++) {
      if (!strcmp(argv[i], "-s") && i + 1 < argc)      stage_name = argv[++i];
      else if (!strcmp(argv[i], "-e") && i + 1 < argc) entry = argv[++i];
      else if (!strcmp(argv[i], "-o") && i + 1 < argc) out = argv[++i];
      else if (!strcmp(argv[i], "-H") && i + 1 < argc) hdr = argv[++i];
      else if (!strcmp(argv[i], "-n") && i + 1 < argc) name = argv[++i];
      else if (argv[i][0] == '-')                     { usage(argv[0]); return 2; }
      else                                            in = argv[i];
   }
   if (!in) { usage(argv[0]); return 2; }

   mesa_shader_stage stage;
   if (!strcmp(stage_name, "vert"))      stage = MESA_SHADER_VERTEX;
   else if (!strcmp(stage_name, "frag")) stage = MESA_SHADER_FRAGMENT;
   else {
      fprintf(stderr, "borgc-cli: unknown stage '%s' (vert|frag)\n", stage_name);
      return 2;
   }

   size_t words = 0;
   uint32_t *spirv = read_spirv(in, &words);
   if (!spirv) return 1;

   glsl_type_singleton_init_or_ref();

   nir_shader *nir = spirv_to_nir(spirv, words, NULL, stage, entry,
                                  &borg_spirv_options, &borg_nir_options);
   if (!nir) {
      fprintf(stderr, "borgc-cli: SPIR-V → NIR failed for %s (%s stage, entry '%s')\n",
              in, stage_name, entry);
      free(spirv);
      glsl_type_singleton_decref();
      return 1;
   }

   borg_lower_nir_for_borgc(nir);

   /* Two-call protocol: borgc reports the true blob size even when the buffer
    * is too small, so an oversized shader is a clear diagnostic rather than a
    * silent truncation. */
   uint8_t blob[8192];
   uint32_t len = 0;
   uint32_t n_instrs = borgc_compile_nir(nir, blob, sizeof blob, &len);
   int rc = 0;

   if (len == 0) {
      fprintf(stderr, "borgc-cli: %s produced an empty blob\n", in);
      rc = 1;
   } else if (len > sizeof blob) {
      fprintf(stderr, "borgc-cli: %s needs %u bytes, buffer is %zu\n",
              in, len, sizeof blob);
      rc = 1;
   } else {
      fprintf(stderr, "borgc-cli: %s → %u instrs, %u byte blob\n", in, n_instrs, len);
      if (out) {
         FILE *f = fopen(out, "wb");
         if (!f || fwrite(blob, 1, len, f) != len) {
            fprintf(stderr, "borgc-cli: cannot write %s\n", out);
            rc = 1;
         }
         if (f) fclose(f);
      }
      if (hdr && !rc) {
         const char *n = name ? name : "borg_shader";
         rc = write_header(hdr, n, blob, len);
      }
   }

   ralloc_free(nir);
   free(spirv);
   glsl_type_singleton_decref();
   return rc;
}
